FROM centos:latest
LABEL maintainer="jamithireddyprudhvi0906@gmail.com"
RUN yum install -y httpd \
 zip\
 unzip
ADD https://github.com/jamithiprudhvi/photogenic.git /var/www/html/
WORKDIR /var/www/html/
RUN cp -rvf photogenic/*
RUN rm -rf photogenic 
CMD ["usr/sbin/https", "-D", "FOREGROUND"]
EXPOSE 80 


